//! Minimal safe RAII wrapper around the [DiligentEngine](https://github.com/DiligentGraphics/DiligentEngine)
//! (DiligentCore) C API generated by `diligent-sys`.
//!
//! # Scope
//!
//! The wrapper covers the resource surface a wgpu backend replacement needs
//! (M1 milestone of the "wgpu -> Diligent" migration):
//!
//! * [`EngineFactoryD3D12`] - factory entry point (`Diligent_GetEngineFactoryD3D12`).
//! * [`RenderDevice`] - device object creation (`IRenderDevice`): buffers,
//!   textures (`create_texture`), texture views (`create_texture_view`),
//!   samplers (`create_sampler`), shaders from HLSL (`create_shader`) or
//!   bytecode/SPIR-V (`create_shader_spirv`), PRS, PSO, fence.
//! * [`DeviceContext`] - immediate context state + draw commands (`IDeviceContext`).
//! * [`SwapChain`] - presentation (`ISwapChain`).
//! * [`Buffer`], [`Texture`], [`TextureView`], [`Sampler`], [`Shader`],
//!   [`PipelineResourceSignature`], [`PipelineState`],
//!   [`ShaderResourceBinding`], [`Fence`] - the resource objects.
//! * [`format`] - the bidirectional wgpu <-> Diligent texture format mapping
//!   table, including the documented Depth24Plus landing and the sRGB
//!   dual-view helper.
//!
//! Everything else in `diligent-sys` remains reachable through
//! [`diligent_sys::bindings`](diligent_sys::bindings) for escape hatches.
//!
//! # Memory model
//!
//! Every wrapped Diligent interface is reference counted (see
//! `IObject::AddRef/Release` in the engine). All owning wrappers
//! ([`Buffer`], [`Shader`], [`Texture`], [`Sampler`], [`PipelineState`], ...)
//! call `Release` on `Drop`, so leaking raw engine objects is not possible
//! through this API. Ownership can be shared explicitly with
//! [`Handle::add_ref`] (COM `AddRef`, the primitive for the
//! `WgpuWrapper`/Arc cloning semantics of M1b). Handles returned
//! **without** a reference count increment are wrapped as [`NonOwning`]
//! (e.g. `SwapChain::current_back_buffer_rtv`,
//! `Texture::get_default_view`) and never released.
//!
//! # Threading
//!
//! No wrapper implements `Send`/`Sync`. In particular, a [`DeviceContext`]
//! must only ever be used from the thread it was created on - Diligent
//! command recording is not thread safe. The device and resource objects
//! (`IRenderDevice`, `IBuffer`, `ITexture`, `ISampler`, `IPipelineState`, ...)
//! are thread safe in Diligent, but this crate keeps them pinned to their
//! creating thread until a deliberate opt-in; cross-thread usage requires
//! `unsafe` access through `as_raw()` and is the caller's responsibility.
//!
//! # Examples
//!
//! See `examples/triangle.rs` (winit 0.30 + D3D12) for the full
//! PRS -> PSO -> SRB -> draw -> present round trip.

pub mod context;
pub mod desc;
pub mod device;
pub mod error;
pub mod factory;
pub mod format;
pub mod handle;
pub mod resource;
pub mod sampler;
pub mod swapchain;
pub mod texture;

pub use context::DeviceContext;
pub use desc::*;
pub use device::RenderDevice;
pub use error::{Error, Result};
pub use factory::EngineFactoryD3D12;
pub use handle::{Handle, NonOwning};
pub use resource::{
    Buffer, Fence, PipelineResourceSignature, PipelineState, PipelineStateCache, Shader,
    ShaderResourceBinding,
};
pub use sampler::Sampler;
pub use swapchain::SwapChain;
pub use texture::{Texture, TextureView};

/// Re-export of the raw bindings crate, for escape hatches and for
/// constructing raw description structs that this wrapper does not cover.
pub use diligent_sys;

#[cfg(test)]
mod tests {
    use super::*;

    /// `Diligent_GetEngineFactoryD3D12()` must return a non-null factory.
    #[test]
    fn factory_d3d12_resolves() {
        let factory = EngineFactoryD3D12::d3d12();
        assert!(factory.is_ok(), "factory creation failed: {:?}", factory.err());
    }

    /// Factory -> device + context creation must succeed and the device
    /// must report `RENDER_DEVICE_TYPE_D3D12`.
    #[test]
    fn device_and_context_create_as_d3d12() {
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context creation");
        let info = device.device_info();
        assert_eq!(
            info.Type,
            diligent_sys::bindings::RENDER_DEVICE_TYPE::RENDER_DEVICE_TYPE_D3D12,
            "device type is not D3D12"
        );
    }

    /// `create_swap_chain` with a null `hwnd` must return `Err` without
    /// crashing (error-path smoke).
    #[test]
    fn swap_chain_null_hwnd_fails() {
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, context) = factory
            .create_device_and_contexts()
            .expect("device+context");
        let result = factory.create_swap_chain(&device, &context, std::ptr::null_mut(), 640, 480);
        assert!(result.is_err(), "null hwnd should have failed");
    }

    /// Create-and-drop cycle must not crash or leak (run several iterations
    /// to exercise ref-count churn).
    #[test]
    fn create_drop_cycle_is_safe() {
        for _ in 0..3 {
            let factory = EngineFactoryD3D12::d3d12().expect("factory");
            let (device, context) = factory
                .create_device_and_contexts()
                .expect("device+context");
            drop(context);
            drop(device);
            drop(factory);
        }
    }

    /// `Handle::add_ref` shares one engine object between several handles;
    /// dropping them in any order must not double-free (reference counting
    /// verified through the engine's own counter).
    #[test]
    fn handle_add_ref_shared_ownership_does_not_double_free() {
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");

        let buffer = device
            .create_buffer(
                "add_ref_test",
                16,
                diligent_sys::bindings::_BIND_FLAGS::BIND_UNIFORM_BUFFER
                    as diligent_sys::bindings::BIND_FLAGS,
                diligent_sys::bindings::_USAGE::USAGE_DEFAULT
                    as diligent_sys::bindings::USAGE,
                0,
                None,
            )
            .expect("buffer");

        for _ in 0..3 {
            let h1 = buffer.add_ref();
            let h2 = h1.add_ref();
            assert_eq!(h2.strong_ref_count(), 3, "two add_refs, three owners");
            drop(h1);
            assert_eq!(h2.strong_ref_count(), 2);
            drop(h2);
            assert_eq!(buffer.strong_ref_count(), 1);
        }
        drop(buffer);
    }

    /// Texture creation (with initial data), default-view borrow and an
    /// owned view with an sRGB format override (the dual-view path).
    #[test]
    fn texture_creation_smoke() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");

        let data = [0u8; 4 * 4 * 4]; // 4x4 Rgba8
        let texture = device
            .create_texture(
                "texture_smoke",
                4,
                4,
                1,
                1,
                sys::_TEXTURE_FORMAT::TEX_FORMAT_RGBA8_UNORM as sys::TEXTURE_FORMAT,
                sys::_BIND_FLAGS::BIND_SHADER_RESOURCE as sys::BIND_FLAGS,
                sys::_USAGE::USAGE_IMMUTABLE as sys::USAGE,
                1,
                Some(&data),
            )
            .expect("texture");

        let default_srv = texture
            .get_default_view(sys::_TEXTURE_VIEW_TYPE::TEXTURE_VIEW_SHADER_RESOURCE as sys::TEXTURE_VIEW_TYPE)
            .expect("default SRV");
        assert!(!default_srv.as_ptr().is_null());

        // sRGB dual view: same texture, format overridden in the view desc.
        let srv_desc = desc::texture_view(
            sys::_TEXTURE_VIEW_TYPE::TEXTURE_VIEW_SHADER_RESOURCE as sys::TEXTURE_VIEW_TYPE,
            Some(sys::_TEXTURE_FORMAT::TEX_FORMAT_RGBA8_UNORM_SRGB as sys::TEXTURE_FORMAT),
            0,
            1,
            0,
            1,
        );
        let srgb_view = device
            .create_texture_view(&texture, &srv_desc)
            .expect("sRGB view over linear texture");
        assert!(!srgb_view.as_raw().is_null());
        drop(srgb_view);
        drop(texture);
    }

    /// Texture without initial data (USAGE_DEFAULT), mip chain 0 (full).
    #[test]
    fn texture_without_initial_data_ok() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");
        let texture = device
            .create_texture(
                "texture_default",
                8,
                8,
                1,
                0,
                sys::_TEXTURE_FORMAT::TEX_FORMAT_RGBA8_UNORM as sys::TEXTURE_FORMAT,
                sys::_BIND_FLAGS::BIND_SHADER_RESOURCE as sys::BIND_FLAGS,
                sys::_USAGE::USAGE_DEFAULT as sys::USAGE,
                1,
                None,
            )
            .expect("texture");
        drop(texture);
    }

    /// Regression: initial data must match the subresource size exactly.
    /// `TextureSubResData` has no size field - the engine copies
    /// `Stride x Height` bytes unconditionally, so a shorter slice would be
    /// read out of bounds. The wrapper must reject it before the engine.
    #[test]
    fn texture_initial_data_length_is_validated() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");

        // 2x2 RGBA8: one subresource is exactly 16 bytes.
        let exact = [0u8; 16];
        let short = [0u8; 15];

        let too_short = device.create_texture(
            "texture_too_short",
            2,
            2,
            1,
            1,
            sys::_TEXTURE_FORMAT::TEX_FORMAT_RGBA8_UNORM as sys::TEXTURE_FORMAT,
            sys::_BIND_FLAGS::BIND_SHADER_RESOURCE as sys::BIND_FLAGS,
            sys::_USAGE::USAGE_IMMUTABLE as sys::USAGE,
            1,
            Some(&short),
        );
        assert!(
            too_short.is_err(),
            "initial data shorter than the subresource must be rejected"
        );

        let exact_len = device.create_texture(
            "texture_exact_len",
            2,
            2,
            1,
            1,
            sys::_TEXTURE_FORMAT::TEX_FORMAT_RGBA8_UNORM as sys::TEXTURE_FORMAT,
            sys::_BIND_FLAGS::BIND_SHADER_RESOURCE as sys::BIND_FLAGS,
            sys::_USAGE::USAGE_IMMUTABLE as sys::USAGE,
            1,
            Some(&exact),
        );
        assert!(
            exact_len.is_ok(),
            "exact-length initial data must be accepted: {:?}",
            exact_len.err()
        );
    }

    /// Sampler creation, both linear and anisotropic flavors; the aniso
    /// guard must reject mixed filters.
    #[test]
    fn sampler_creation_smoke() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");

        let linear = desc::sampler(
            sys::_FILTER_TYPE::FILTER_TYPE_LINEAR as sys::FILTER_TYPE,
            sys::_FILTER_TYPE::FILTER_TYPE_LINEAR as sys::FILTER_TYPE,
            sys::_FILTER_TYPE::FILTER_TYPE_LINEAR as sys::FILTER_TYPE,
            sys::_TEXTURE_ADDRESS_MODE::TEXTURE_ADDRESS_WRAP as sys::TEXTURE_ADDRESS_MODE,
            sys::_TEXTURE_ADDRESS_MODE::TEXTURE_ADDRESS_WRAP as sys::TEXTURE_ADDRESS_MODE,
            sys::_TEXTURE_ADDRESS_MODE::TEXTURE_ADDRESS_WRAP as sys::TEXTURE_ADDRESS_MODE,
            None,
            0,
            0.0,
            f32::MAX,
        );
        let sampler = device
            .create_sampler("sampler_linear", &linear)
            .expect("linear sampler");
        drop(sampler);

        let aniso = desc::sampler(
            sys::_FILTER_TYPE::FILTER_TYPE_ANISOTROPIC as sys::FILTER_TYPE,
            sys::_FILTER_TYPE::FILTER_TYPE_ANISOTROPIC as sys::FILTER_TYPE,
            sys::_FILTER_TYPE::FILTER_TYPE_ANISOTROPIC as sys::FILTER_TYPE,
            sys::_TEXTURE_ADDRESS_MODE::TEXTURE_ADDRESS_CLAMP as sys::TEXTURE_ADDRESS_MODE,
            sys::_TEXTURE_ADDRESS_MODE::TEXTURE_ADDRESS_CLAMP as sys::TEXTURE_ADDRESS_MODE,
            sys::_TEXTURE_ADDRESS_MODE::TEXTURE_ADDRESS_CLAMP as sys::TEXTURE_ADDRESS_MODE,
            None,
            16,
            0.0,
            f32::MAX,
        );
        let sampler = device
            .create_sampler("sampler_aniso", &aniso)
            .expect("anisotropic sampler");
        drop(sampler);

        let mixed = desc::sampler(
            sys::_FILTER_TYPE::FILTER_TYPE_LINEAR as sys::FILTER_TYPE,
            sys::_FILTER_TYPE::FILTER_TYPE_ANISOTROPIC as sys::FILTER_TYPE,
            sys::_FILTER_TYPE::FILTER_TYPE_LINEAR as sys::FILTER_TYPE,
            sys::_TEXTURE_ADDRESS_MODE::TEXTURE_ADDRESS_WRAP as sys::TEXTURE_ADDRESS_MODE,
            sys::_TEXTURE_ADDRESS_MODE::TEXTURE_ADDRESS_WRAP as sys::TEXTURE_ADDRESS_MODE,
            sys::_TEXTURE_ADDRESS_MODE::TEXTURE_ADDRESS_WRAP as sys::TEXTURE_ADDRESS_MODE,
            None,
            8,
            0.0,
            f32::MAX,
        );
        assert!(
            device.create_sampler("sampler_mixed", &mixed).is_err(),
            "anisotropy with mixed filters must be rejected"
        );
    }

    /// SPIR-V entry point validation (the D3D12 machine cannot consume
    /// SPIR-V, so only argument validation is exercised here).
    #[test]
    fn create_shader_spirv_validation() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");
        let stage = sys::_SHADER_TYPE::SHADER_TYPE_VERTEX as sys::SHADER_TYPE;

        assert!(device.create_shader_spirv("s", &[], stage).is_err());
        assert!(device.create_shader_spirv("s", &[1, 2, 3], stage).is_err());
        assert!(device.create_shader_spirv("s", &[1, 2, 3, 4], stage).is_err());
    }

    /// MSAA texture creation: a SampleCount 4 texture reports back
    /// `SampleCount == 4` through `GetDesc`, and SampleCount 1 stays 1.
    #[test]
    fn msaa_texture_sample_count() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");
        let format = sys::_TEXTURE_FORMAT::TEX_FORMAT_RGBA8_UNORM as sys::TEXTURE_FORMAT;

        let msaa = device
            .create_texture(
                "msaa_texture",
                16,
                16,
                1,
                1,
                format,
                sys::_BIND_FLAGS::BIND_RENDER_TARGET as sys::BIND_FLAGS,
                sys::_USAGE::USAGE_DEFAULT as sys::USAGE,
                4,
                None,
            )
            .expect("4x MSAA texture");
        assert_eq!(
            msaa.sample_count().expect("desc"),
            4,
            "the texture must report SampleCount 4"
        );

        let single = device
            .create_texture(
                "single_sample_texture",
                16,
                16,
                1,
                1,
                format,
                sys::_BIND_FLAGS::BIND_RENDER_TARGET as sys::BIND_FLAGS,
                sys::_USAGE::USAGE_DEFAULT as sys::USAGE,
                1,
                None,
            )
            .expect("single-sample texture");
        assert_eq!(single.sample_count().expect("desc"), 1);
    }

    /// Compute pipeline creation: a trivial compute shader + empty PRS array
    /// must yield a pipeline whose desc reports `PIPELINE_TYPE_COMPUTE`.
    #[test]
    fn compute_pipeline_creation_smoke() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");

        let shader = device
            .create_shader(
                "compute_identity",
                "[numthreads(1, 1, 1)]\nvoid main(uint3 dtid : SV_DispatchThreadID) {}",
                sys::_SHADER_TYPE::SHADER_TYPE_COMPUTE as sys::SHADER_TYPE,
            )
            .expect("compute shader");

        let pso = device
            .create_compute_pipeline("compute_pipeline", &shader, &[])
            .expect("compute pipeline");
        let desc = pso.desc().expect("pso desc");
        assert_eq!(
            desc.PipelineType,
            sys::_PIPELINE_TYPE::PIPELINE_TYPE_COMPUTE as sys::PIPELINE_TYPE,
            "the pipeline must report the compute type"
        );
        drop(pso);
        drop(shader);
    }

    /// Buffer readback roundtrip: `update_buffer` on a DEFAULT buffer,
    /// `copy_buffer` into a staging buffer, then `map_buffer(MAP_READ)` must
    /// return the written bytes. The map guard unmaps on drop.
    ///
    /// The D3D12 backend never waits for the GPU when mapping staging
    /// resources (DeviceContextD3D12Impl.cpp: "D3D12 backend never waits
    /// for GPU when mapping staging buffers for reading"), so the read is
    /// fenced: `enqueue_signal` after the copy + `fence.wait` before the
    /// map.
    #[test]
    fn buffer_readback_roundtrip() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, context) = factory
            .create_device_and_contexts()
            .expect("device+context");

        let data: Vec<u8> = (0..256u32).map(|i| (i % 251) as u8).collect();
        let src = device
            .create_buffer(
                "readback_src",
                data.len() as u64,
                0,
                sys::_USAGE::USAGE_DEFAULT as sys::USAGE,
                0,
                None,
            )
            .expect("source buffer");
        let staging = device
            .create_staging_buffer("readback_staging", data.len() as u64)
            .expect("staging buffer");
        let fence = device.create_fence("readback_fence").expect("fence");

        context.update_buffer(&src, 0, &data).expect("update");
        context
            .copy_buffer(&src, 0, &staging, 0, data.len() as u64)
            .expect("copy");
        context.enqueue_signal(&fence, 1).expect("signal");
        context.flush();
        fence.wait(1).expect("wait for the copy");

        let mapped = context
            .map_buffer(&staging, sys::_MAP_TYPE::MAP_READ as sys::MAP_TYPE, false)
            .expect("map must not fail")
            .expect("synchronous map must succeed");
        assert_eq!(mapped.as_slice(), &data[..], "readback data must match");
        drop(mapped);
        drop(staging);
        drop(src);
    }

    /// Texture readback roundtrip: `copy_texture` into a staging texture and
    /// a fenced `map_texture_subresource(MAP_READ)` must return the written
    /// texels (rows `Stride` bytes apart).
    #[test]
    fn texture_readback_roundtrip() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, context) = factory
            .create_device_and_contexts()
            .expect("device+context");
        let format = sys::_TEXTURE_FORMAT::TEX_FORMAT_RGBA8_UNORM as sys::TEXTURE_FORMAT;

        // 8x2 Rgba8: pixel (x, y) = (x, 128 + y) so rows differ.
        let mut data = Vec::with_capacity(8 * 2 * 4);
        for y in 0..2u32 {
            for x in 0..8u32 {
                data.extend_from_slice(&[x as u8, 128 + y as u8, 0, 255]);
            }
        }
        // USAGE_IMMUTABLE (initial data is only honored for immutable
        // resources without a context; USAGE_DEFAULT would ignore the data).
        let src = device
            .create_texture(
                "readback_tex_src",
                8,
                2,
                1,
                1,
                format,
                0,
                sys::_USAGE::USAGE_IMMUTABLE as sys::USAGE,
                1,
                Some(&data),
            )
            .expect("source texture");
        let staging = device
            .create_staging_texture("readback_tex_staging", 8, 2, format)
            .expect("staging texture");
        let fence = device.create_fence("readback_tex_fence").expect("fence");

        context
            .copy_texture(&src, 0, 0, &staging, 0, 0)
            .expect("copy");
        context.enqueue_signal(&fence, 1).expect("signal");
        context.flush();
        fence.wait(1).expect("wait for the copy");

        let mapped = context
            .map_texture_subresource(
                &staging,
                0,
                0,
                sys::_MAP_TYPE::MAP_READ as sys::MAP_TYPE,
                false,
            )
            .expect("map must not fail")
            .expect("synchronous map must succeed");
        let stride = mapped.stride();
        assert!(stride >= 8 * 4, "stride must cover a row: {stride}");
        for y in 0..2usize {
            let row = unsafe { std::slice::from_raw_parts(mapped.row(y), 8 * 4) };
            for x in 0..8usize {
                assert_eq!(
                    row[x * 4..x * 4 + 4],
                    [x as u8, 128 + y as u8, 0, 255],
                    "texel ({x}, {y}) must match"
                );
            }
        }
        drop(mapped);
        drop(staging);
        drop(src);
    }

    /// `MAP_FLAG_DO_NOT_WAIT` must never error: it returns `Ok(Some)` when
    /// the copy is already visible and `Ok(None)` otherwise.
    #[test]
    fn map_do_not_wait_never_fails() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, context) = factory
            .create_device_and_contexts()
            .expect("device+context");

        let staging = device
            .create_staging_buffer("readback_dnw", 64)
            .expect("staging buffer");
        let result = context.map_buffer(
            &staging,
            sys::_MAP_TYPE::MAP_READ as sys::MAP_TYPE,
            true,
        );
        assert!(
            result.is_ok(),
            "DO_NOT_WAIT map must not fail"
        );
        // Drop the mapped view before the buffer (the map borrows the
        // buffer's raw pointer; unmapping a released buffer is UB).
        drop(result);
        drop(staging);
    }

    /// M3b §8.10: the in-memory pipeline-state cache must create in
    /// `LOAD_STORE` mode on D3D12, survive a create/drop cycle without
    /// leaking, and serialize an (initially empty) library blob through
    /// `get_data` without failing.
    #[test]
    fn pipeline_state_cache_create_and_get_data() {
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");

        let cache = device
            .create_pipeline_state_cache("test_pso_cache")
            .expect("pipeline-state cache");
        assert!(!cache.as_raw().is_null());

        // An empty library serializes to a (possibly empty) blob without
        // error; the write side stays available for the post-L4 disk path.
        let blob = cache.get_data().expect("GetData");
        assert!(!blob.is_empty(), "D3D12 pipeline library blob should be non-empty");

        // PSO creation with the cache in the `pPSOCache` slot must succeed
        // and store/load through the cache (a smoke smoke - the engine's
        // same-name lookup path). Shader sources mirror the triangle example
        // (ATTRIB0 layout + SV_POSITION/SV_TARGET), which is known to
        // compile+create on D3D12.
        use diligent_sys::bindings as sys;
        let shader = device
            .create_shader(
                "cache_vs",
                "struct VSInput { float3 pos : ATTRIB0; };\n\
                 struct VSOutput { float4 pos : SV_POSITION; };\n\
                 void main(in VSInput input, out VSOutput output) {\n\
                     output.pos = float4(input.pos, 1.0);\n\
                 }",
                sys::_SHADER_TYPE::SHADER_TYPE_VERTEX as sys::SHADER_TYPE,
            )
            .expect("vs");
        let ps = device
            .create_shader(
                "cache_ps",
                "                 struct PSInput { float4 pos : SV_POSITION; };\n\
                 float4 main(in PSInput input) : SV_TARGET {\n\
                     return float4(1.0, 0.0, 0.0, 1.0);\n\
                 }",
                sys::_SHADER_TYPE::SHADER_TYPE_PIXEL as sys::SHADER_TYPE,
            )
            .expect("ps");
        let prs = device
            .create_pipeline_resource_signature("cache_prs", &[])
            .expect("prs");
        let layout = [desc::layout_element(
            c"ATTRIB",
            0,
            0,
            3,
            sys::_VALUE_TYPE::VT_FLOAT32 as sys::VALUE_TYPE,
            false,
        )];
        let mut blend: sys::BlendStateDesc = unsafe { std::mem::zeroed() };
        blend.RenderTargets[0].RenderTargetWriteMask =
            sys::_COLOR_MASK::COLOR_MASK_ALL as sys::COLOR_MASK;
        let mut ds: sys::DepthStencilStateDesc = unsafe { std::mem::zeroed() };
        ds.DepthEnable = false;
        ds.DepthWriteEnable = false;
        let mut ra: sys::RasterizerStateDesc = unsafe { std::mem::zeroed() };
        ra.FillMode = sys::_FILL_MODE::FILL_MODE_SOLID as sys::FILL_MODE;
        ra.CullMode = sys::_CULL_MODE::CULL_MODE_NONE as sys::CULL_MODE;
        ra.DepthClipEnable = true;
        let pso = device
            .create_graphics_pipeline_multi_rt_cached(
                "cached_pipeline",
                &shader,
                Some(&ps),
                std::slice::from_ref(
                    &(sys::_TEXTURE_FORMAT::TEX_FORMAT_RGBA8_UNORM as sys::TEXTURE_FORMAT),
                ),
                &blend.RenderTargets,
                &layout,
                &[&prs],
                sys::_TEXTURE_FORMAT::TEX_FORMAT_UNKNOWN as sys::TEXTURE_FORMAT,
                &ra,
                &ds,
                sys::_PRIMITIVE_TOPOLOGY::PRIMITIVE_TOPOLOGY_TRIANGLE_LIST
                    as sys::PRIMITIVE_TOPOLOGY,
                1,
                desc::DEFAULT_SAMPLE_MASK,
                Some(&cache),
            )
            .expect("cached graphics pipeline");

        assert!(!pso.as_raw().is_null());

        // After one store the library blob grows (the driver serialized the
        // stored PSO), proving the PSO was stored in the cache.
        let blob_after = cache.get_data().expect("GetData after store");
        assert!(
            blob_after.len() >= blob.len(),
            "storing a PSO must not shrink the cache blob ({} -> {})",
            blob.len(),
            blob_after.len()
        );

        drop(pso);
        drop(prs);
        drop(ps);
        drop(shader);
        drop(cache);
    }

    /// The cache create/drop cycle must not crash or leak (several
    /// iterations to exercise ref-count churn).
    #[test]
    fn pipeline_state_cache_create_drop_cycle_is_safe() {
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");
        for i in 0..3 {
            let cache = device
                .create_pipeline_state_cache(&format!("pso_cache_cycle_{i}"))
                .expect("cache");
            drop(cache);
        }
    }

    /// M5a (task 16.1): the native D3D12 device handle escape hatch must
    /// resolve on a D3D12 device to a non-null `ID3D12Device*`, and the
    /// interface release after the call must not disturb the device (the
    /// returned handle is borrowed, so a second resolution returns the same
    /// pointer - the engine hands out the same internal object).
    #[test]
    fn native_d3d12_device_escape_hatch() {
        use diligent_sys::bindings as sys;
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");

        let first = device
            .native_d3d12_device()
            .expect("native device resolution must not fail");
        let Some(first) = first else {
            panic!("a D3D12 device must expose IRenderDeviceD3D12");
        };
        assert!(!first.is_null(), "native ID3D12Device must be non-null");

        // Resolving again yields the same internal object (the engine's
        // D3D12 device instance), proving the borrowed-handle contract.
        let second = device
            .native_d3d12_device()
            .expect("second resolution must not fail")
            .expect("still a D3D12 device");
        assert_eq!(first, second, "the native device pointer must be stable");

        // The pointer is a valid COM interface: its vtable is readable and
        // the QueryInterface/Release slots are present (a smoke dereference
        // of the first vtable slots).
        let vtbl = unsafe { &*(*first.cast::<sys::IObject>()).pVtbl };
        assert!(
            vtbl.Object.QueryInterface.is_some() && vtbl.Object.Release.is_some(),
            "the native device must be a COM interface"
        );
    }

    /// The escape hatch must always resolve on a D3D12 device (guards the
    /// contract from regressing to a silent `None`).
    #[test]
    fn native_d3d12_device_is_always_some_on_d3d12() {
        let factory = EngineFactoryD3D12::d3d12().expect("factory");
        let (device, _context) = factory
            .create_device_and_contexts()
            .expect("device+context");
        let handle = device
            .native_d3d12_device()
            .expect("resolution must not fail")
            .expect("D3D12 device must always expose the native handle");
        assert!(!handle.is_null());
    }
}
