//! Raw FFI bindings to the [DiligentEngine](https://github.com/DiligentGraphics/DiligentEngine)
//! (DiligentCore) C API, generated by `bindgen`, plus the native
//! `DiligentCore` static library built by `build.rs` via CMake.
//!
//! This is a plain bindings crate: there is **no runtime translation layer**.
//! Everything re-exported here is the raw `extern "C"` surface of Diligent.
//!
//! # Usage
//!
//! The bindings are generated into `OUT_DIR/bindings.rs` at build time and
//! re-exported from this crate root, so `use diligent_sys::*;` is enough to
//! reach every struct, enum, constant and function.
//!
//! # Entry points
//!
//! Diligent's C API creates engine factories through global entry functions:
//!
//! * [`Diligent_GetEngineFactoryD3D12`] - Direct3D12 backend (Windows).
//! * [`Diligent_GetEngineFactoryVk`] - Vulkan backend (Linux/Android/macOS).
//!
//! The returned factory implements [`IEngineFactory`] /
//! [`IEngineFactoryD3D12`] / [`IEngineFactoryVk`]. Interface instances are
//! handles (`pVtbl` pointers), and methods are called through the generated
//! Vtbl function-pointer fields — there are **no** standalone
//! `I<Interface>_<Method>(This, ...)` functions in the bindings. In
//! Diligent's C headers those names are function-like macros expanding to a
//! Vtbl call (e.g. `CALL_IFACE_METHOD(EngineFactoryD3D12,
//! CreateDeviceAndContextsD3D12, This, ...)`), and macros are not emitted by
//! bindgen. Each generated Vtbl nests one `I<Interface>Methods` struct per
//! base interface in the inheritance chain (e.g. `IEngineFactoryD3D12Vtbl`
//! contains `Object`, `EngineFactory` and `EngineFactoryD3D12`), so a
//! factory-creation call is written as:
//!
//! ```text
//! let pFactory = bindings::Diligent_GetEngineFactoryD3D12();
//! let create_device = (*(*pFactory).pVtbl)
//!     .EngineFactoryD3D12
//!     .CreateDeviceAndContextsD3D12
//!     .unwrap(); // method field is Option<unsafe extern "C" fn(...)>
//! unsafe { create_device(pFactory, &engine_ci, &mut device, &mut contexts) };
//! ```
//!
//! # Core interfaces
//!
//! The bindings cover the whole C API under
//! `Graphics/GraphicsEngine/interface/`:
//!
//! * [`IRenderDevice`], [`IDeviceContext`], [`ISwapChain`]
//! * [`IPipelineState`], [`IPipelineResourceSignature`], [`IShaderResourceBinding`]
//! * [`IBuffer`], [`ITexture`], [`ISampler`], [`IShader`], [`IFence`], ...
//!
//! # Linking
//!
//! `build.rs` builds DiligentCore with CMake (Windows: D3D12 backend only)
//! and emits `cargo:rustc-link-lib` directives for the combined
//! `DiligentCore` static library and the system libraries it needs
//! (`d3d12`, `dxgi`, `d3dcompiler`, `shlwapi`). Set `DILIGENT_SKIP_CMAKE=1`
//! to skip the native build (bindgen only). See `README.md` for the full
//! three-platform build matrix.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(clippy::missing_safety_doc)]

/// The complete generated FFI surface.
pub mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use bindings::*;

// ---------------------------------------------------------------------------
// Link fuse
// ---------------------------------------------------------------------------

/// Forces the final link to keep the `DiligentCore` static library alive even
/// when no bindings symbol is referenced directly, so that `cargo build`
/// genuinely validates the native library link (cmake build + system libs).
///
/// Only emitted when build.rs actually linked the native library
/// (`cargo:rustc-cfg=diligent_native_linked`), so the `DILIGENT_SKIP_CMAKE=1`
/// degradation path (bindgen only) still compiles.
#[cfg(diligent_native_linked)]
#[used]
#[doc(hidden)]
pub static DILIGENT_LINK_FUSE: unsafe extern "C" fn() -> *mut bindings::IEngineFactoryD3D12 =
    bindings::Diligent_GetEngineFactoryD3D12;
